#!/bin/bash

# Show the help for the program
if [ $# -eq "0" ] || [ $1 == "-h" ]; then
    # If arguments are provided, and the first argument is the help flag, show the help page
    echo ""
    echo "cloud [-a|-r|-l] [instance name] [instance ip:port]"
    echo ""
    echo "Manage cloud instances via setting up ssh connections and keys - cloud provides the utility of registering a"
    echo "rsa key with an instance and aliasing the instance ssh connection for quick access."
    echo ""
    echo "Example:"
    echo "    cloud -a dev 10.63.43.134"
    echo "    # Registers key... requires password... aliases.... then"
    echo "    sshdev  # Logs you straight into the instance"
    echo ""
    return
fi

removeKey () {
    # Remove the IP Key if it has already been set

    ip=$(cat "$HOME/.bash_aliases" | grep "ssh$1" | cut -f2 -d @ | tr -d \")

    if [ "$ip" != "" ]; then
        ssh-keygen -R "$ip"
    fi
}

if [ $1 == "-a" ]; then

    # Check as to whether this is an update - remove the previous key if set
    removeKey "$2"

    # Generate and copy local key across for use
    ssh-copy-id "$3" || { echo "Failed to copy password across"; return; }

    # Create ssh alias for quick access
    strong alias "ssh$2"="ssh -o ServerAliveInterval=30 $3"
    return
fi

if [ $1 == "-r" ]; then

    # Extract the IP from the alias - remove the key to the ip
    removeKey "$2"

    # Unalias the key
    strong unalias "ssh$2"

    return
fi

if [ $1 == "-l" ]; then
    sed -n -e '/ssh/p' ~/.bash_aliases
    return
fi